config/routes.rb
Hondana::Application.routes.draw do
  post "information/send_mail" => "information#send_mail", format: false
  get "information/:action" => "information#:action", format: false

  get "property/show" => "property#show", format: false
  get "property/edit" => "property#edit", format: false
  patch "property/update" => "property#update", format: false

  get "messages" => "messages#index", format: false
  post "messages/read" => "messages#read"

  get "members" => "members#index", format: false
  post "members/login" => "members#authenticate", format: false
  post "members/confirm" => "members#confirm", format: false
  post "members/create" => "members#create", format: false
  post "members/send_mail_token" => "members#send_mail_token", format: false
  post "members/reset_password" => "members#reset_password", format: false
  patch "members/update" => "members#update", format: false
  patch "members/update_password" => "members#update_password", format: false
  get "members/login_as/:id" => "members#login_as", format: false
  get "members/:action" => "members#:action", format: false
  get "members/evaluation" => "members#evaluation", format: false
  get "members/evaluations/:member_id" => "members#evaluations", format: false

  get "back" => "application#back", format: false

  get "books/list" => "books#list", format: false
  get "books/search" => "books#search", format: false
  get "books/search_edit" => "books#search_edit", format: false
  get "books/search_detail" => "books#search_detail", format: false
  post "books/favorite" => "books#favorite", format: false
  get "books/delete_favorite" => "books#delete_favorite", format: false
  get "books/show_image/:isbn" => "books#show_image", format: false

  resources :collections, only: [:index, :new, :show] do
    resources :receiver_evaluations, only: [:new, :create]
    resources :sender_evaluations, only: [:new, :create]
    collection do
      get 'index'
      post 'create'
      get 'edit'
      patch 'update'
      get 'destroy'
      get 'list'
      post 'confirm'
      get 'complete'
      get 'confirm_request'
      post 'request_collection'
      get 'download_label'
      post 'complete_sending'
    end

    member do
      get 'member_list'
    end
  end

  resources :books, format: false
  resources :notices, format: false
  resources :genres, format: false

  root 'information#top'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :check_admin
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.where(delete_flg: false).order(sort: :asc)
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)
    @genre.delete_flg = false
    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'ジャンルが登録されました。' }
        format.json { render action: 'show', status: :created, location: @genre }
      else
        format.html { render action: 'new' }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'ジャンルが修正されました。' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name, :description, :sort, :delete_flg)
    end
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="name">名前</label>
    <p>
    <%= f.text_field :name %>
    </p>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <p>
    <%= f.text_area :description, cols: 40, rows: 4 %>
    </p>
  </div>
  <div class="field">
    <%= f.label :sort %><br>
    <p>
    <%= f.number_field :sort %>
    </p>
  </div>
  <div class="field">
    <%= f.submit "登録" %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>ジャンル編集</h1><% @title = "ジャンル編集" %>

<%= render 'form' %>

<p><%= link_to '表示', @genre %> | <%= link_to '戻る', genres_path %></p>

app/views/genres/index.html.erb
<h1>ジャンル一覧</h1><% @title = "ジャンル一覧" %>

<table class="list">
  <thead>
    <tr>
      <th>名前</th>
      <th>内容</th>
      <th>表示順</th>
      <th>表示</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td class="nowrap"><%= genre.name %></td>
        <td><%= genre.description %></td>
        <td><%= genre.sort %></td>
        <td class="center"><%= link_to '表示', genre %></td>
        <td class="center"><%= link_to '編集', edit_genre_path(genre) %></td>
        <td class="center"><%= link_to '削除', genre, method: :delete, data: { confirm: '削除してよろしいですか?(書籍のジャンル情報、会員お気に入りのジャンル情報も失われます)' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
<%= link_to '新規登録', new_genre_path %> | <%= link_to "戻る", "/information/admin" %>
</p>

app/views/genres/new.html.erb
<h1>ジャンル新規登録</h1><% @title = "ジャンル新規登録" %>

<%= render 'form' %>

<p><%= link_to '戻る', genres_path %></p>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<div class="field">
  <label for="name">名前</label>
  <p><%= @genre.name %></p>
</div>

<div class="field">
  <%= label_tag :content, "内容" %>
  <p><%= @genre.description %></p>
</div>

<div class="field">
  <%= label_tag :sort, "表示順" %>
  <p><%= @genre.sort %></p>
</div>

<p><%= link_to '編集', edit_genre_path(@genre) %> | <%= link_to '戻る', genres_path %></p>