config/routes.rb
Hondana::Application.routes.draw do
  post "information/send_mail" => "information#send_mail", format: false
  get "information/:action" => "information#:action", format: false

  get "property/show" => "property#show", format: false
  get "property/edit" => "property#edit", format: false
  patch "property/update" => "property#update", format: false

  get "messages" => "messages#index", format: false
  post "messages/read" => "messages#read"

  get "members" => "members#index", format: false
  post "members/login" => "members#authenticate", format: false
  post "members/confirm" => "members#confirm", format: false
  post "members/create" => "members#create", format: false
  post "members/send_mail_token" => "members#send_mail_token", format: false
  post "members/reset_password" => "members#reset_password", format: false
  patch "members/update" => "members#update", format: false
  patch "members/update_password" => "members#update_password", format: false
  get "members/login_as/:id" => "members#login_as", format: false
  get "members/:action" => "members#:action", format: false
  get "members/evaluation" => "members#evaluation", format: false
  get "members/evaluations/:member_id" => "members#evaluations", format: false

  get "back" => "application#back", format: false

  get "books/list" => "books#list", format: false
  get "books/search" => "books#search", format: false
  get "books/search_edit" => "books#search_edit", format: false
  get "books/search_detail" => "books#search_detail", format: false
  post "books/favorite" => "books#favorite", format: false
  get "books/delete_favorite" => "books#delete_favorite", format: false
  get "books/show_image/:isbn" => "books#show_image", format: false

  resources :collections, only: [:index, :new, :show] do
    resources :receiver_evaluations, only: [:new, :create]
    resources :sender_evaluations, only: [:new, :create]
    collection do
      get 'index'
      post 'create'
      get 'edit'
      patch 'update'
      get 'destroy'
      get 'list'
      post 'confirm'
      get 'complete'
      get 'confirm_request'
      post 'request_collection'
      get 'download_label'
      post 'complete_sending'
    end

    member do
      get 'member_list'
    end
  end

  resources :books, format: false
  resources :notices, format: false
  resources :genres, format: false

  root 'information#top'

end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :check_admin
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.order(notice_date: :desc)
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'お知らせが作成されました。' }
        format.json { render action: 'show', status: :created, location: @notice }
      else
        format.html { render action: 'new' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'お知らせが更新されました。' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:content, :notice_date)
    end
end

app/views/notices/_form.html.erb
<%= form_for(@notice) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notice_date %><br>
    <p>
    	<%= f.datetime_select :notice_date, use_month_numbers: true %><br />
 	 	トップページに時刻は表示されませんが、同一日に新しい順に表示するために使用されます。
 	</p>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <p>
	    <%= f.text_area :content, cols: 40, rows: 4 %><br />
	    改行は空白として表示されます。
 	</p>
  </div>
  <div class="actions">
    <p><%= f.submit value: "登録" %></p>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>お知らせ編集</h1><% @title = "お知らせ編集" %>

<%= render 'form' %>

<p><%= link_to '表示', @notice %> |
<%= link_to '戻る', notices_path %></p>

app/views/notices/index.html.erb
<h1>お知らせ一覧</h1><% @title = "お知らせ一覧" %>

<% if @notices.blank? %>
	<p>お知らせはありません。</p>
<% else %>
<table class="list">
  <thead>
    <tr>
      <th>お知らせ日時</th>
      <th>内容</th>
      <th>表示</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= format_datetime notice.notice_date %></td>
        <td><%= notice.content %></td>
        <td class="center"><%= link_to '表示', notice %></td>
        <td class="center"><%= link_to '編集', edit_notice_path(notice) %></td>
        <td class="center"><%= link_to '削除', notice, method: :delete, data: { confirm: '削除してよろしいですか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<p><%= link_to '新規追加', new_notice_path %> |  <%= link_to "戻る", "/information/admin" %></p>

app/views/notices/new.html.erb
<h1>お知らせ新規追加</h1><% @title = "お知らせ新規追加" %>

<%= render 'form' %>

<p><%= link_to '戻る', notices_path %></p>

app/views/notices/show.html.erb
<h1>お知らせ内容</h1><% @title = "お知らせ内容" %>
<p id="notice"><%= notice %></p>

<div class="field">
  <%= label_tag :notice_date, "お知らせ日時" %>
  <p><%= format_datetime @notice.notice_date %></p>
</div>

<div class="field">
  <%= label_tag :content, "内容" %>
  <p><%= @notice.content %></p>
</div>

<p><%= link_to '編集', edit_notice_path(@notice) %> |
<%= link_to '戻る', notices_path %></p>