config/routes.rb
Hondana::Application.routes.draw do
  post "information/send_mail" => "information#send_mail", format: false
  get "information/:action" => "information#:action", format: false

  get "property/show" => "property#show", format: false
  get "property/edit" => "property#edit", format: false
  patch "property/update" => "property#update", format: false

  get "messages" => "messages#index", format: false
  post "messages/read" => "messages#read"

  get "members" => "members#index", format: false
  post "members/login" => "members#authenticate", format: false
  post "members/confirm" => "members#confirm", format: false
  post "members/create" => "members#create", format: false
  post "members/send_mail_token" => "members#send_mail_token", format: false
  post "members/reset_password" => "members#reset_password", format: false
  patch "members/update" => "members#update", format: false
  patch "members/update_password" => "members#update_password", format: false
  get "members/login_as/:id" => "members#login_as", format: false
  get "members/:action" => "members#:action", format: false
  get "members/evaluation" => "members#evaluation", format: false
  get "members/evaluations/:member_id" => "members#evaluations", format: false

  get "back" => "application#back", format: false

  get "books/list" => "books#list", format: false
  get "books/search" => "books#search", format: false
  get "books/search_edit" => "books#search_edit", format: false
  get "books/search_detail" => "books#search_detail", format: false
  post "books/favorite" => "books#favorite", format: false
  get "books/delete_favorite" => "books#delete_favorite", format: false
  get "books/show_image/:isbn" => "books#show_image", format: false

  resources :collections, only: [:index, :new, :show] do
    resources :receiver_evaluations, only: [:new, :create]
    resources :sender_evaluations, only: [:new, :create]
    collection do
      get 'index'
      post 'create'
      get 'edit'
      patch 'update'
      get 'destroy'
      get 'list'
      post 'confirm'
      get 'complete'
      get 'confirm_request'
      post 'request_collection'
      get 'download_label'
      post 'complete_sending'
    end

    member do
      get 'member_list'
    end
  end

  resources :books, format: false
  resources :notices, format: false
  resources :genres, format: false

  root 'information#top'

end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  skip_before_action :check_logined
  before_action :check_admin, only: :admin

  def top
    @books = Book.where(delete_flg: false, member_id: nil).order(created_at: :desc).limit(20)
    @notices = Notice.order(notice_date: :desc).limit(5)
    render layout: false
  end

  def inquiry
    if session[:id].present?
      member = Member.find(session[:id])
      @name = member.name
      @mail_address = member.mail_address
    end
  end

  def send_mail
    name = params[:name]
    mail_address = params[:mail_address]
    category_id = params[:category_id]
    content = params[:content]
    if name.blank?
      @notice = "お名前が記載されていません。"
    elsif mail_address !~ /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
      @notice = "メールアドレスの形式に誤りがあります。"
    elsif content.blank?
      @notice = "お問い合わせ内容が記載されていません。"
    else
      category = Array["会員登録・退会について", "本の登録・検索について", "ポイントについて", "本の発送について", "その他"][category_id.to_i]
      NoticeMailer.inquiry(name, mail_address, category, content).deliver
      return
    end
    render action: "inquiry"
  end
end

app/views/information/_term.html.erb
<h2 class="members_terms_title">利用規約</h2>
<p class="terms">この利用規約(リンク先のプライバシーポリシー、その他利用ガイドを含め、以下「本規約」といいます)は、スピカ旅行社（以下「当社」といいます）が「ホンダナ」の名称で提供・運営する一切のサービス（以下「本サービス」といいます）の利用に関して、本サービスを利用するお客様と当社との間で、その諸条件を定めるものです。</p>
<p class="terms">本サービスの利用者は、本サービスを利用するにあたって本規約の内容を十分理解した上でその内容を遵守することに同意して本サービスを利用するものとし、<br>
  本サービスを利用した場合には、当該利用者は本規約を遵守することに同意したものとみなします。<br>
</p>
<h2 class="terms_title">本サービスについて</h2>
<h3 class="terms_article">第1条（本サービスの内容）</h3>
<p class="terms">1. 本サービスは、当社が会員（本規約を承認し、本サービスを利用するために当社所定の入会登録を行い、当社がその入会登録を承認した個人および法人をいいます）に対し、
  本サービスに登録した会員同士の間で商品（本サービスにおいて取引の目的となる物品をいいます）を交換する機会を提供するサービスです。<br>
  会員は、本サービスを利用して、商品を出品（会員が、本サービスにて、必要なコンテンツを書き込むなどにより他の会員等が閲覧可能となり、
  商品を取引できる状態にすることをいいます）し、他の会員と商品の交換をすることができます。<br>
なお、本規約上「コンテンツ」とは、当社または会員等が本サービスに掲載または発信した画像、映像およびテキスト情報、プログラム、ノウハウその他本サービスに関する一切の内容を指します。</p>
<p class="terms">2. 商品の交換契約は、その商品の出品者（本サービスを通じて商品を出品する会員をいいます）と交換申請者（本サービスを通じて商品の交換を希望する会員をいいます）との間で直接に成立します。<br>
当社は、会員に対し商品を交換する機会を提供するのみで、商品の交換契約の当事者にはなりません。</p>
<p class="terms">3. 会員は、お客様同士の取引に関する一切の事項（会員登録、商品の出品・交換申請・交換申請の承認、商品の発送・受領、<br>
  交換契約の取消・解除、商品の瑕疵担保責任、商品の返品・商品代金の返金等を含みますが、これに限られないものとします）について責任を負います。<br>
  当社は、会員同士のトラブルに原則として介入しないものとし、会員は当社にトラブルの解決を求めることはできないものとします。<br>
  ただし、当社は、本サービスの円滑な運営のために必要であると当社が判断した場合には、会員同士のトラブルに介入することができるものとします。<br>
</p>
<h3 class="terms_article">第2条（本サービスの利用条件）</h3>
<p class="terms">1. 本サービスを利用するためには、本規約に同意頂いた上で、本規約に定めるところに従い会員登録を行う必要があります。<br>
  本規約に同意頂けない場合は、当社が提供する本サービスをご利用頂くことはできません。<br>
なお、本サービスを利用された場合には、本規約に同意頂いたものとみなします。</p>
<p class="terms">2. 本規約は、全ての会員に適用され、会員登録手続時および登録後に、遵守頂く必要があります。<br>
  会員がインターネット回線を通じて行った登録、出品、購入、退会その他の手続は、当社のサーバーに当該手続に関するデータが送信され、
  当社のシステムに当該手続の内容が反映された時点をもって有効に成立するものとします。<br>
</p>
<h3 class="terms_article">第3条（会員登録）</h3>
<p class="terms">1. 会員登録を行う者は、その本人が、当社所定の手続に従い会員登録申請を行うものとします。</p>
<p class="terms">2. 当社は、以下各号のいずれかに該当する場合、当該登録申請を承認しないことがあります。<br>
  (1)過去に本規約違反等により、当社から会員登録の取消等の処分を受けている場合<br>
  (2)申請内容に虚偽の事項が含まれている場合<br>
  (3)暴力団、暴力団員、暴力団準構成員、総会屋、社会運動等標榜ゴロ、特殊知能暴力集団その他これに準じる反社会的勢力<br>
  （以下「反社会的勢力等」といいます）であると判明した場合または反社会的勢力等が経営に実質的に関与している法人等であると判明した場合<br>
(4)その他登録申請を承認することが不適当であると当社が判断する場合</p>
<p class="terms">3. 登録内容の変更がある場合は、会員は、直ちに当社所定の手続により登録内容を変更しなければならず、常に会員自身の正確な情報が登録されているよう、登録内容を管理および修正する責任を負います。</p>
<p class="terms">4. 登録内容に変更があったにもかかわらず、会員が当社所定の手続により変更の届出をしていない場合、当社は、登録内容の変更のないものとして取り扱うことができます。<br>
  変更の届出があった場合でも、変更登録前に行われた取引や各種手続は、変更登録前の情報に依拠する場合があります。<br>
  <br>
5. 会員が会員登録や登録内容の変更をしたことにより生じた損害に関し、直接的か間接的かを問わず、当社は一切責任を負わないものとします。</p>
<p class="terms">6. 未成年者の方は、会員になることができません。未成年者が会員になるためには、会員となることおよび本規約に従って本サービスを利用し、<br>
  出品または交換その他一切の処分行為を行うことについて、事前に親権者の包括的な同意を得なければなりません。<br>
  また、当該未成年者は、親権者の同意の有無について、当社から親権者に対し、確認の連絡をする場合があることにあらかじめ同意します。<br>
  <br>
  7. 会員は複数の会員アカウントを持つことができないものとします。<br>
</p>
<h3 class="terms_article">第4条（ログインIDとパスワードの管理等）</h3>
<p class="terms">1. 会員は、登録したログインIDおよびパスワードを自己の責任と費用にて管理するものとし、会員資格、ログインIDおよびパスワードを第三者に利用させたり、<br>
譲渡、売買、質入、貸与、賃貸したり、その他形態を問わず処分することはできません。</p>
<p class="terms">2. ログインIDおよびパスワードの管理不十分による情報の漏洩、使用上の過誤、第三者の使用、不正アクセス等による損害の責任は会員が負うものとし、当社は一切責任を負わないものとします。<br>
万一、ログインIDおよびパスワードが不正に利用されたことにより当社に損害が生じた場合、会員は当該損害を賠償するものとします。</p>
<p class="terms">3. ログインIDおよびパスワードの情報が第三者に漏洩した場合またはそのおそれがある場合、速やかに当社まで連絡するとともに、当社の指示がある場合にはこれに従うものとします。<br>
</p>
<h3 class="terms_article">第5条（会員資格の取消等）</h3>
<p class="terms">1. 当社は、会員が以下の各号のいずれかに該当した場合または該当したと当社が判断した場合、事前の通知なく、会員資格の取消、会員に関連するコンテンツや情報の全部もしくは一部の削除、
  本サービスの全部もしくは一部へのアクセスの拒否または機能制限等の措置をとることができるものとします。<br>
  その場合、当社は、その理由を説明する義務を負わないものとします。<br>
  (1)法令または本規約に違反した場合<br>
  (2)不正行為があった場合<br>
  (3)会員が登録した情報が虚偽の情報である場合<br>
  (4)会員が本規約上必要となる手続または当社への連絡を行わなかった場合<br>
  (5)会員が登録した情報が既存の登録と重複している場合<br>
  (6)会員が、登録した情報の確認、証明のための資料を提出しない場合<br>
  (7)会員が登録した電話番号、メールアドレス、住所が不通になったことが判明した場合<br>
  (8)会員が、債務超過、無資力、支払停止または支払不能の状態に陥った場合<br>
  (9)決済事業者又は収納代行業者のいずれか一方または双方から、会員による本サービスの利用停止をさせるよう要請があった場合または会員に対する決済サービスの提供停止措置が取られた場合<br>
  (10)会員について破産手続開始、民事再生手続開始、会社更生手続開始、特別清算開始もしくはその他適用ある倒産手続開始の申立が行われた場合または解散もしくは営業停止状態である場合<br>
  (11)会員が法人の場合、その法人の代表者の同意を得ていないことが判明した場合<br>
  (12)過去に本規約に違反し本サービスの利用停止処分となった者である場合<br>
  (13)他の会員や第三者に不当に迷惑をかけた場合<br>
  (14)パスワードの入力に関して当社が判断する一定回数以上の入力ミスがあった場合<br>
  (15)当社が定める一定期間内に一定回数以上のログインがなかった場合<br>
  (16)第3条の会員資格を満たさなくなった場合<br>
  (17)法律行為を有効に行なう能力を有していない場合(法定代理人の同意等によって能力が補完された場合を除きます)<br>
  (18)暴力団、暴力団員、暴力団準構成員、暴力団関係企業、総会屋等、社会運動標ぼうゴロ、政治活動標ぼうゴロ、特殊知能暴力集団、これらの者と密接な関わり（資金その他の便益提供行為を含みます）を有する者およびこれらに準じる者である場合<br>
  (19)会員が自らまたは第三者をして、暴力的な要求行為、法的な責任を超えた不当な要求行為、脅迫的な言動または暴力を用いる行為、風評を流布し、偽計を用いまたは威力を用いて、信用を毀損または業務を妨害する行為をした場合<br>
  (20)その他当社が会員に相応しくないと判断した場合</p>
<p class="terms">2. 当社は、会員資格を取り消された会員に対し、将来にわたって当社が提供する本サービスの利用およびアクセスを禁止することができることとします。</p>
<p class="terms">3. 当社は、本条の措置により生じる損害について、直接的か間接的かを問わず、一切の責任を負わないものとします。</p>
<p class="terms">4. 当社は、本条の措置の時点で当該会員に支払われることとなっていた金銭あるいはポイント等について、当社の判断により、無効とすることができるものとします。<br>
</p>
<h3 class="terms_article">第6条（会員の退会）</h3>
<p class="terms">1. 会員が退会を希望する場合は、当社所定の手続により退会することができます。<br>
ただし、退会の手続を行った時点で、取引の決済や商品の郵送等取引の手続が未完のものがある場合は退会することができませんので、会員は、一連の未完の取引を本規約に従って遅滞なく円滑に進め、完了させた後、退会手続きを行う必要があります。</p>
<p class="terms">2. 当社が退会を認め、会員が退会された時点において、会員に支払われることとなっていた商品代金等の金銭等については、当社の判断により、無効として取扱い、会員に対して返還しない措置を採ることができるものとします。</p>
<p class="terms">3. 当社は、会員による退会手続終了後も、本サービスの円滑な運用に必要な合理的な期間において、会員の退会手続を留保できるものとします。</p>
<p class="terms">4. 当社は、本条の措置により生じる会員の損害について、一切の責任を負わないものとします。<br>
</p>
<h3 class="terms_article">第7条（本の登録）</h3>
<p class="terms">1. 出品者は、当社所定の手続により、商品の出品を行うものとします。</p>
<p class="terms">2. 出品者は、出品者が交換申請に対し承認するまで、出品を取り消すことができます。</p>
<p class="terms">3. 出品者は、「出品禁止リスト」に挙げるものについての出品ができないことについてあらかじめ同意したものとします。<br>
このリストに該当する商品を出品した場合、出品者の故意または過失の有無に関わらず、本規約違反行為とみなします。</p>
<p class="terms">4. 会員が真に出品する意思のない出品、その出品を見た人がその商品情報だけでは正しく商品を理解できないかまたは混乱する可能性のある出品、商品説明で十分な説明を行わない出品等を行ってはなりません。<br>
  出品に関して当社が不適切と判断した場合において、その出品やその出品に対して発生していた購入行為等を当社の判断で取り消すことができるものとし、また、当社の判断により、会員資格の取り消しも行うことができるものとします。<br>
本項に基づく当社の措置によって会員に生じる損害について、直接的か間接的かを問わず、当社は一切責任を負わないものとします。</p>
<p class="terms">5. 会員は、出品にあたっては、古物営業法、特定商取引に関する法律、不当景品類および不当表示防止法、不正競争防止法、商標法、著作権法その他の法律およびガイドライン等を遵守しなければなりません。<br>
</p>
<h3 class="terms_article">第8条（商品の交換申請）</h3>
<p class="terms">1. 交換申請者は、当社所定の手続により、出品者が出品した商品の交換申請を行うものとします。</p>
<p class="terms">2. 交換申請者は交換申請を行った後は、交換申請を取り消すことはできません。</p>
<p class="terms">3. 会員は、真に交換する意思がないにもかかわらず、交換申請をしてはなりません。当該交換申請によって、会員等及び第三者に生じる損害につき、直接的か間接的かを問わず、当社は一切責任を負わないものとします。</p>
<p class="terms">4. 出品者が、交換申請者による交換申請があった日から翌日の23時59分までに当該交換申請を承諾しない場合には、当該交換申請は取り消されるものとします。<br>
</p>
<h3 class="terms_article">第9条（取引）</h3>
<p class="terms">1. 交換申請者からの交換申請に対し、出品者が承諾した時点において、第1条第2項に定めるとおり出品者と交換申請者との間に商品の交換契約が成立するものとします。</p>
<p class="terms">2. 出品者は、交換申請者からの交換申請に対し承諾するか否かを自由に判断することができるものとします。</p>
<p class="terms">3. 交換申請者は、当社の定める方法により、速やかに送料を支払うものとします。<br>
交換申請に対する承諾があった日から数えて翌々日の23時59分までに交換申請者が当該支払いを行わない場合、出品者と交換申請者間の当該商品についての交換契約は当初から交換契約が成立しなかったものとみなされます。</p>
<p class="terms">4. 出品者は、交換申請者がブクによる決済を完了させた後1週間以内に商品の発送を完了し、交換申請者に対し発送済みの連絡をするものとします。</p>
<p class="terms">5. 交換申請者は、出品者から商品を受領した場合、直ちに商品の数量、内容、品質、瑕疵の有無等を確認し、当社の定める方法により、速やかに商品を受領したことを出品者に対し通知し、出品者を評価するものとします。</p>
<p class="terms">6. 出品者および交換申請者は、交換契約に基づき発生した権利を第三者に譲渡し、担保に供するなど一切の処分をすることはできないものとします。</p>
<p class="terms">7. 取引される商品等に起因する問題またはトラブルは、当事者が自らの費用と責任で解決しなければならず、当社に対し問題の解決を求めることはできません。当社は、商品等に関する問題により会員等に生じた損害や不利益について、一切責任を負いません。</p>
<p class="terms">8. 当社は、本サービスの円滑な運営のために必要と当社が判断した場合には、会員等の商品等に関する問題に介入することができます。</p>
<p class="terms">9. 商品の決済方法に選択した決済事業との間で、商品の所有権の帰属について特約がある場合、この特約にしたがって商品の所有権の帰属が決せられるものとします。</p>
<h3 class="terms_article">14条（当社ポイント「ブク」の取扱い）</h3>
<p class="terms">1.当社サービスの登録・交換は必ず当社ポイント(以下「ブク」といいます)を使用します。<br>
ブクの詳細については利用ガイドに定めるとおりとします。</p>
<p class="terms">2. 会員は、ブクを当社が指定する本サービスにおける商品交換以外の、現金、財物その他の経済的利益と交換することはできません。<br>
ただし、法令上必要な場合はこの限りではありません。この場合、ブクの払い戻し方法は、法令に従って当社が定め、当社のアプリ等に表示するところに従うものとします。</p>
<p class="terms">3. ブクの有効期限は、ブクが加算された日から6ヶ月を過ぎた時点までとします。有効期限を過ぎた未使用のブクは失効し、その後再度利用することはできません。<br>
また当社は、期間を定めたブクを付与することがあり、その場合は、会員が当社の定める期間を超えて当該対象取引を行わなかった場合、ブクは自動的に消滅します。</p>
<p class="terms">4. 会員が退会した場合または会員資格が消滅した場合、不正にブクを取得したことが発覚した場合、当該時点において保有するブクは、理由のいかんを問わず、すべて失効するものとします。</p>

app/views/information/aboutus.html.erb
<h1>会社概要</h1><% @title = "会社概要" %>
<p>会社名　スピカ旅行社</p>
<p>所在地　〒010-0001 秋田県秋田市中通5-4-18</p>
<p>お問い合わせ　info@spica-travel.com</p>

app/views/information/admin.html.erb
<h1>管理者メニュー</h1><% @title = "管理者メニュー" %>

<p><%= link_to "お知らせ管理", notices_path %></p>

<p><%= link_to "ジャンル管理", genres_path %></p>

<p><%= link_to "書籍管理", books_path %></p>

<p><%= link_to "会員管理", members_path %></p>

<p><%= link_to "プロパティ", "/property/show" %></p>

app/views/information/faq_book.html.erb
<h1 id="index">FAQ（準備中）</h1><% @title = "FAQ 蔵書の登録について" %>
<div class="faqmenu">
<ul>
<li><%= link_to "よくある質問", "/information/faq"  %></li>
<li><%= link_to "ホンダナの基本", "/information/faq_kihon"  %></li>
<li><%= link_to "会員情報の登録・変更について", "/information/faq_member"  %></li>
<li><%= link_to "蔵書の登録について", "/information/faq_book"  %></li>
<li><%= link_to "本をさがす・交換申請をする", "/information/faq_search"  %></li>
<li><%= link_to "（出品者）取引について", "/information/faq_syuppin"  %></li>
<li><%= link_to "（購入者）取引について", "/information/faq_kounyu"  %></li>
<li><%= link_to "取引全般について", "/information/faq_zenpan"  %></li>
<li><%= link_to "配送・決済について", "/information/faq_haiso"  %></li>
<li><%= link_to "ブクについて", "/information/faq_buku"  %></li>
</div>

<h2>【蔵書の登録について】</h2>
<ul id="faq">
<p>［～について］</p>
	<li>Q1.　<a href="#1">ーーー</a></li>
	<li>Q2.　<a href="#2">ーーー</a></li>
	<li>Q3.　<a href="#3">ーーー</a></li>
	<li>Q4.　<a href="#4">ーーー</a></li>
</ul>
<br><br>
<div id="1">
	<h2 class="faq"> Q1. ーーー</h2>
A.<%= link_to "お問い合わせ", "/information/inquiry"  %>ください。<br><br>
<div class="right"><div class="right"><div class="right"><a class="button" href="#index">▲ Top</a></div></div></div>
</div>

<div id="2">
	<h2 class="faq"> Q2. ーーー</h2>
A.<%= link_to "お問い合わせ", "/information/inquiry"  %>ください。<br><br>
<div class="right"><div class="right"><div class="right"><a class="button" href="#index">▲ Top</a></div></div></div>
</div>

<div id="3">
	<h2 class="faq"> Q3. ーーー</h2>
A.<%= link_to "お問い合わせ", "/information/inquiry"  %>ください。<br><br>
<div class="right"><div class="right"><div class="right"><a class="button" href="#index">▲ Top</a></div></div></div>
</div>

<div id="4">
	<h2 class="faq"> Q4. ーーー</h2>
A.<%= link_to "お問い合わせ", "/information/inquiry"  %>ください。<br><br>
<div class="right"><div class="right"><div class="right"><a class="button" href="#index">▲ Top</a></div></div></div>
</div>

app/views/information/faq_buku.html.erb
<h1 id="index">FAQ（準備中）</h1><% @title = "FAQ ブクについて" %>
<div class="faqmenu">
<ul>
<li><%= link_to "よくある質問", "/information/faq"  %></li>
<li><%= link_to "ホンダナの基本", "/information/faq_kihon"  %></li>
<li><%= link_to "会員情報の登録・変更について", "/information/faq_member"  %></li>
<li><%= link_to "蔵書の登録について", "/information/faq_book"  %></li>
<li><%= link_to "本をさがす・交換申請をする", "/information/faq_search"  %></li>
<li><%= link_to "（出品者）取引について", "/information/faq_syuppin"  %></li>
<li><%= link_to "（購入者）取引について", "/information/faq_kounyu"  %></li>
<li><%= link_to "取引全般について", "/information/faq_zenpan"  %></li>
<li><%= link_to "配送・決済について", "/information/faq_haiso"  %></li>
<li><%= link_to "ブクについて", "/information/faq_buku"  %></li>
</div>

<h2>【ブクについて】</h2>
<ul id="faq">
	<li>Q1.　<a href="#1">ーーー</a></li>
	<li>Q2.　<a href="#2">ーーー</a></li>
	<li>Q3.　<a href="#3">ーーー</a></li>
	<li>Q4.　<a href="#4">ーーー</a></li>
</ul>
<br><br>
<div id="1">
	<h2 class="faq"> Q1. ーーー</h2>
A.<%= link_to "お問い合わせ", "/information/inquiry"  %>ください。<br><br>
<div class="right"><div class="right"><div class="right"><a class="button" href="#index">▲ Top</a></div></div></div>
</div>

<div id="2">
	<h2 class="faq"> Q2. ーーー</h2>
A.<%= link_to "お問い合わせ", "/information/inquiry"  %>ください。<br><br>
<div class="right"><div class="right"><div class="right"><a class="button" href="#index">▲ Top</a></div></div></div>
</div>

<div id="3">
	<h2 class="faq"> Q3. ーーー</h2>
A.<%= link_to "お問い合わせ", "/information/inquiry"  %>ください。<br><br>
<div class="right"><div class="right"><div class="right"><a class="button" href="#index">▲ Top</a></div></div></div>
</div>

<div id="4">
	<h2 class="faq"> Q4. ーーー</h2>
A.<%= link_to "お問い合わせ", "/information/inquiry"  %>ください。<br><br>
<div class="right"><div class="right"><div class="right"><a class="button" href="#index">▲ Top</a></div></div></div>
</div>

app/views/information/faq_haiso.html.erb
<h1 id="index">FAQ（準備中）</h1><% @title = "FAQ 配送・決済について" %>
<div class="faqmenu">
<ul>
<li><%= link_to "よくある質問", "/information/faq"  %></li>
<li><%= link_to "ホンダナの基本", "/information/faq_kihon"  %></li>
<li><%= link_to "会員情報の登録・変更について", "/information/faq_member"  %></li>
<li><%= link_to "蔵書の登録について", "/information/faq_book"  %></li>
<li><%= link_to "本をさがす・交換申請をする", "/information/faq_search"  %></li>
<li><%= link_to "（出品者）取引について", "/information/faq_syuppin"  %></li>
<li><%= link_to "（購入者）取引について", "/information/faq_kounyu"  %></li>
<li><%= link_to "取引全般について", "/information/faq_zenpan"  %></li>
<li><%= link_to "配送・決済について", "/information/faq_haiso"  %></li>
<li><%= link_to "ブクについて", "/information/faq_buku"  %></li>
</div>

<h2>【配送・決済について】</h2>
<ul id="faq">
	<li>Q1.　<a href="#1">クリックポストでの決済時にエラーが起き、支払い手続きができません</a></li>
	<li>Q2.　<a href="#2">ーーー</a></li>
	<li>Q3.　<a href="#3">ーーー</a></li>
	<li>Q4.　<a href="#4">ーーー</a></li>
</ul>
<br><br>
<div id="1">
	<h2 class="faq"> Q1. クリックポストでの決済時にエラーが起き、支払い手続きができません</h2>
A.エラーの原因として「ポップアップブロック」が有効になっている可能性が考えられます。<br>
（ポップアップブロックとは、ホームページ閲覧中に表示される小さな別画面（ポップアップウィンドウ）が勝手に表示されることを防ぐ機能です）<br>
インターネットを閲覧する画面（Internet Explorer）の設定を行なってください。<br><br>

<strong>［ポップアップブロックを有効にする］</strong><br>
方法1.「ツール>ポップアップブロック>ポップアップブロックを無効にする」<br>
方法2.「ツール>インターネットオプション>プライバシー>ポップアップブロックを有効にする」のチェックを外す<br><br>

メニューに「ツール」が表示されていない場合はキーボードの「Alt」をインターネットが表示されている画面を開いたまま押すと表示されます。<br><br>

<strong>［Internet Explorer以外］</strong><br>
Google Chrome：インターネットを開いた状態で、右上の横線が三本入った「Menu>設定>詳細設定を表示>コンテンツの設定>すべてのサイトに対してポップアップ表示を許可する」をオン<br><br>

Mac（safari）：左上のメニューの「Safari>環境設定>セキュリティ>ポップアップウィンドウを開かない」のチェックを外す<br><br>

iPhone：ホーム画面>「設定>safari>ポップアップブロックオフ」<br><br>

iPad：ホーム画面>「設定>safari>ポップアップブロックオフ」<br><br>

Galaxy：インターネットを開いた状態で、右上の「Menu>設定>ポップアップブロックのチェックを外す」<br><br>

Xperia：インターネットを開いた状態で、右上の「Menu>設定>高度な設定>ポップアップブロックのチェックを外す」<br><br>
<div class="right"><div class="right"><div class="right"><a class="button" href="#index">▲ Top</a></div></div></div>
</div>